# Generated by Django 3.2.16 on 2024-02-02 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='description',
            field=models.TextField(blank=True, help_text='пара слов о сотруднике', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='birthday',
            name='salary',
            field=models.IntegerField(default='10', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Зарплата'),
        ),
    ]
