# Generated by Django 3.2.16 on 2024-02-02 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20240202_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='email',
            field=models.EmailField(default='example@contoso.com', max_length=30, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='salary',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(100000)], verbose_name='Зарплата (руб)'),
        ),
    ]
