# Generated by Django 3.2.16 on 2024-02-02 16:11

import birthday.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_auto_20240202_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.DateField(validators=[birthday.validators.real_age], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='email',
            field=models.EmailField(default='example@contoso.com', max_length=30, unique=True, verbose_name='Электронная почта'),
        ),
    ]
